// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package vergeio

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	// Communicator configuration fields (embedded from communicator.Config)
	// These fields enable SSH/WinRM connectivity for provisioning
	Type               *string `mapstructure:"communicator" cty:"communicator" hcl:"communicator"`
	PauseBeforeConnect *string `mapstructure:"pause_before_connecting" cty:"pause_before_connecting" hcl:"pause_before_connecting"`
	// SSH-specific fields
	SSHHost                   *string `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort                   *int    `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port"`
	SSHUsername               *string `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username"`
	SSHPassword               *string `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHPrivateKeyFile         *string `mapstructure:"ssh_private_key_file" cty:"ssh_private_key_file" hcl:"ssh_private_key_file"`
	SSHCertificateFile        *string `mapstructure:"ssh_certificate_file" cty:"ssh_certificate_file" hcl:"ssh_certificate_file"`
	SSHPty                    *bool   `mapstructure:"ssh_pty" cty:"ssh_pty" hcl:"ssh_pty"`
	SSHTimeout                *string `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout"`
	SSHAgentAuth              *bool   `mapstructure:"ssh_agent_auth" cty:"ssh_agent_auth" hcl:"ssh_agent_auth"`
	SSHDisableAgentForwarding *bool   `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding" hcl:"ssh_disable_agent_forwarding"`
	SSHHandshakeAttempts      *int    `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts" hcl:"ssh_handshake_attempts"`
	SSHBastionHost            *string `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host" hcl:"ssh_bastion_host"`
	SSHBastionPort            *int    `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port" hcl:"ssh_bastion_port"`
	SSHBastionAgentAuth       *bool   `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth" hcl:"ssh_bastion_agent_auth"`
	SSHBastionUsername        *string `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username" hcl:"ssh_bastion_username"`
	SSHBastionPassword        *string `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password" hcl:"ssh_bastion_password"`
	SSHBastionInteractive     *bool   `mapstructure:"ssh_bastion_interactive" cty:"ssh_bastion_interactive" hcl:"ssh_bastion_interactive"`
	SSHBastionPrivateKeyFile  *string `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file" hcl:"ssh_bastion_private_key_file"`
	SSHBastionCertificateFile *string `mapstructure:"ssh_bastion_certificate_file" cty:"ssh_bastion_certificate_file" hcl:"ssh_bastion_certificate_file"`
	SSHFileTransferMethod     *string `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method" hcl:"ssh_file_transfer_method"`
	SSHProxyHost              *string `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host" hcl:"ssh_proxy_host"`
	SSHProxyPort              *int    `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port" hcl:"ssh_proxy_port"`
	SSHProxyUsername          *string `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username" hcl:"ssh_proxy_username"`
	SSHProxyPassword          *string `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password" hcl:"ssh_proxy_password"`
	SSHKeepAliveInterval      *string `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval" hcl:"ssh_keep_alive_interval"`
	SSHReadWriteTimeout       *string `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout" hcl:"ssh_read_write_timeout"`
	// WinRM-specific fields
	WinRMUser     *string `mapstructure:"winrm_username" cty:"winrm_username" hcl:"winrm_username"`
	WinRMPassword *string `mapstructure:"winrm_password" cty:"winrm_password" hcl:"winrm_password"`
	WinRMHost     *string `mapstructure:"winrm_host" cty:"winrm_host" hcl:"winrm_host"`
	WinRMNoProxy  *bool   `mapstructure:"winrm_no_proxy" cty:"winrm_no_proxy" hcl:"winrm_no_proxy"`
	WinRMPort     *int    `mapstructure:"winrm_port" cty:"winrm_port" hcl:"winrm_port"`
	WinRMTimeout  *string `mapstructure:"winrm_timeout" cty:"winrm_timeout" hcl:"winrm_timeout"`
	WinRMUseSSL   *bool   `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl" hcl:"winrm_use_ssl"`
	WinRMInsecure *bool   `mapstructure:"winrm_insecure" cty:"winrm_insecure" hcl:"winrm_insecure"`
	WinRMUseNTLM  *bool   `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm" hcl:"winrm_use_ntlm"`
	// Shutdown configuration fields
	ShutdownCommand *string `mapstructure:"shutdown_command" cty:"shutdown_command" hcl:"shutdown_command"`
	ShutdownTimeout *string `mapstructure:"shutdown_timeout" cty:"shutdown_timeout" hcl:"shutdown_timeout"`
	// Power-on timeout configuration fields
	PowerOnTimeout *string `mapstructure:"power_on_timeout" cty:"power_on_timeout" hcl:"power_on_timeout"`
	BootTimeout    *string `mapstructure:"boot_timeout" cty:"boot_timeout" hcl:"boot_timeout"`
	// ClusterConfig fields
	Username *string `mapstructure:"vergeio_username" required:"false" cty:"vergeio_username" hcl:"vergeio_username"`
	Password *string `mapstructure:"vergeio_password" required:"false" cty:"vergeio_password" hcl:"vergeio_password"`
	Insecure *bool   `mapstructure:"vergeio_insecure" required:"false" cty:"vergeio_insecure" hcl:"vergeio_insecure"`
	Endpoint *string `mapstructure:"vergeio_endpoint" required:"false" cty:"vergeio_endpoint" hcl:"vergeio_endpoint"`
	Port     *int    `mapstructure:"vergeio_port" required:"false" cty:"vergeio_port" hcl:"vergeio_port"`
	// VmConfig fields
	Machine              *int                `mapstructure:"machine" required:"false" cty:"machine" hcl:"machine"`
	Name                 *string             `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
	Cluster              *string             `mapstructure:"cluster" required:"false" cty:"cluster" hcl:"cluster"`
	Description          *string             `mapstructure:"description" required:"false" cty:"description" hcl:"description"`
	Enabled              *bool               `mapstructure:"enabled" required:"false" cty:"enabled" hcl:"enabled"`
	MachineType          *string             `mapstructure:"machine_type" required:"false" cty:"machine_type" hcl:"machine_type"`
	AllowHotplug         *bool               `mapstructure:"allow_hotplug" required:"false" cty:"allow_hotplug" hcl:"allow_hotplug"`
	DisablePowercycle    *bool               `mapstructure:"disable_powercycle" required:"false" cty:"disable_powercycle" hcl:"disable_powercycle"`
	CPUCores             *int                `mapstructure:"cpu_cores" required:"false" cty:"cpu_cores" hcl:"cpu_cores"`
	CPUType              *string             `mapstructure:"cpu_type" required:"false" cty:"cpu_type" hcl:"cpu_type"`
	RAM                  *int                `mapstructure:"ram" required:"false" cty:"ram" hcl:"ram"`
	Console              *string             `mapstructure:"console" required:"false" cty:"console" hcl:"console"`
	Display              *string             `mapstructure:"display" required:"false" cty:"display" hcl:"display"`
	Video                *string             `mapstructure:"video" required:"false" cty:"video" hcl:"video"`
	Sound                *string             `mapstructure:"sound" required:"false" cty:"sound" hcl:"sound"`
	OSFamily             *string             `mapstructure:"os_family" required:"false" cty:"os_family" hcl:"os_family"`
	OSDescription        *string             `mapstructure:"os_description" required:"false" cty:"os_description" hcl:"os_description"`
	RTCBase              *string             `mapstructure:"rtc_base" required:"false" cty:"rtc_base" hcl:"rtc_base"`
	BootOrder            *string             `mapstructure:"boot_order" required:"false" cty:"boot_order" hcl:"boot_order"`
	ConsolePassEnabled   *bool               `mapstructure:"console_pass_enabled" required:"false" cty:"console_pass_enabled" hcl:"console_pass_enabled"`
	ConsolePass          *string             `mapstructure:"console_pass" required:"false" cty:"console_pass" hcl:"console_pass"`
	USBTablet            *bool               `mapstructure:"usb_tablet" required:"false" cty:"usb_tablet" hcl:"usb_tablet"`
	UEFI                 *bool               `mapstructure:"uefi" required:"false" cty:"uefi" hcl:"uefi"`
	SecureBoot           *bool               `mapstructure:"secure_boot" required:"false" cty:"secure_boot" hcl:"secure_boot"`
	SerialPort           *bool               `mapstructure:"serial_port" required:"false" cty:"serial_port" hcl:"serial_port"`
	BootDelay            *int                `mapstructure:"boot_delay" required:"false" cty:"boot_delay" hcl:"boot_delay"`
	PreferredNode        *string             `mapstructure:"preferred_node" required:"false" cty:"preferred_node" hcl:"preferred_node"`
	SnapshotProfile      *string             `mapstructure:"snapshot_profile" required:"false" cty:"snapshot_profile" hcl:"snapshot_profile"`
	CloudInitDataSource  *string             `mapstructure:"cloud_init_data_source" required:"false" cty:"cloud_init_data_source" hcl:"cloud_init_data_source"`
	PowerState           *bool               `mapstructure:"power_state" required:"false" cty:"power_state" hcl:"power_state"`
	GuestAgent           *bool               `mapstructure:"guest_agent" required:"false" cty:"guest_agent" hcl:"guest_agent"`
	HAGroup              *string             `mapstructure:"ha_group" required:"false" cty:"ha_group" hcl:"ha_group"`
	Advanced             *string             `mapstructure:"advanced" required:"false" cty:"advanced" hcl:"advanced"`
	NestedVirtualization *bool               `mapstructure:"nested_virtualization" required:"false" cty:"nested_virtualization" hcl:"nested_virtualization"`
	DisableHypervisor    *bool               `mapstructure:"disable_hypervisor" required:"false" cty:"disable_hypervisor" hcl:"disable_hypervisor"`
	VmDiskConfigs        []FlatVmDiskConfig  `mapstructure:"vm_disks" required:"false" cty:"vm_disks" hcl:"vm_disks"`
	VmNicConfigs         []FlatVmNicConfig   `mapstructure:"vm_nics" required:"false" cty:"vm_nics" hcl:"vm_nics"`
	CloudInitFiles       []FlatCloudInitFile `mapstructure:"cloud_init_files" required:"false" cty:"cloud_init_files" hcl:"cloud_init_files"`
}

// FlatVmDiskConfig is an auto-generated flat version of VmDiskConfig.
type FlatVmDiskConfig struct {
	Machine             *int    `mapstructure:"machine" required:"false" cty:"machine" hcl:"machine"`
	Name                *string `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
	Description         *string `mapstructure:"description" required:"false" cty:"description" hcl:"description"`
	Interface           *string `mapstructure:"interface" required:"false" cty:"interface" hcl:"interface"`
	Media               *string `mapstructure:"media" required:"false" cty:"media" hcl:"media"`
	MediaSource         *int    `mapstructure:"media_source" required:"false" cty:"media_source" hcl:"media_source"`
	PreferredTier       *string `mapstructure:"preferred_tier" required:"false" cty:"preferred_tier" hcl:"preferred_tier"`
	DiskSize            *int64  `mapstructure:"disksize" required:"false" cty:"disksize" hcl:"disksize"`
	Enabled             *bool   `mapstructure:"enabled" required:"false" cty:"enabled" hcl:"enabled"`
	ReadOnly            *bool   `mapstructure:"readonly" required:"false" cty:"readonly" hcl:"readonly"`
	Serial              *string `mapstructure:"serial" required:"false" cty:"serial" hcl:"serial"`
	Asset               *string `mapstructure:"asset" required:"false" cty:"asset" hcl:"asset"`
	OrderId             *int    `mapstructure:"orderid" required:"false" cty:"orderid" hcl:"orderid"`
	PreserveDriveFormat *bool   `mapstructure:"preserve_drive_format" required:"false" cty:"preserve_drive_format" hcl:"preserve_drive_format"`
}

// FlatVmNicConfig is an auto-generated flat version of VmNicConfig.
type FlatVmNicConfig struct {
	Machine         *int    `mapstructure:"machine" required:"false" cty:"machine" hcl:"machine"`
	Name            *string `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
	Description     *string `mapstructure:"description" required:"false" cty:"description" hcl:"description"`
	Interface       *string `mapstructure:"interface" required:"false" cty:"interface" hcl:"interface"`
	Driver          *string `mapstructure:"driver" required:"false" cty:"driver" hcl:"driver"`
	Model           *string `mapstructure:"model" required:"false" cty:"model" hcl:"model"`
	VNET            *int    `mapstructure:"vnet" required:"false" cty:"vnet" hcl:"vnet"`
	MAC             *string `mapstructure:"macaddress" required:"false" cty:"macaddress" hcl:"macaddress"`
	IPAddress       *string `mapstructure:"ipaddress" required:"false" cty:"ipaddress" hcl:"ipaddress"`
	AssignIPAddress *bool   `mapstructure:"assign_ipaddress" required:"false" cty:"assign_ipaddress" hcl:"assign_ipaddress"`
	Enabled         *bool   `mapstructure:"enabled" required:"false" cty:"enabled" hcl:"enabled"`
}

// FlatCloudInitFile is an auto-generated flat version of CloudInitFile.
type FlatCloudInitFile struct {
	Name     *string  `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
	Contents *string  `mapstructure:"contents" required:"false" cty:"contents" hcl:"contents"`
	Files    []string `mapstructure:"files" required:"false" cty:"files" hcl:"files"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// FlatMapstructure returns a new FlatVmDiskConfig.
func (*VmDiskConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVmDiskConfig)
}

// FlatMapstructure returns a new FlatVmNicConfig.
func (*VmNicConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVmNicConfig)
}

// FlatMapstructure returns a new FlatCloudInitFile.
func (*CloudInitFile) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCloudInitFile)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		// Communicator configuration fields for SSH/WinRM connectivity
		"communicator":            &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"pause_before_connecting": &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		// SSH-specific configuration fields
		"ssh_host":                     &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                     &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_username":                 &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"ssh_password":                 &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_private_key_file":         &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"ssh_certificate_file":         &hcldec.AttrSpec{Name: "ssh_certificate_file", Type: cty.String, Required: false},
		"ssh_pty":                      &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"ssh_timeout":                  &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"ssh_agent_auth":               &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"ssh_disable_agent_forwarding": &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"ssh_handshake_attempts":       &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"ssh_bastion_host":             &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"ssh_bastion_port":             &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"ssh_bastion_agent_auth":       &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"ssh_bastion_username":         &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"ssh_bastion_password":         &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"ssh_bastion_interactive":      &hcldec.AttrSpec{Name: "ssh_bastion_interactive", Type: cty.Bool, Required: false},
		"ssh_bastion_private_key_file": &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"ssh_bastion_certificate_file": &hcldec.AttrSpec{Name: "ssh_bastion_certificate_file", Type: cty.String, Required: false},
		"ssh_file_transfer_method":     &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"ssh_proxy_host":               &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"ssh_proxy_port":               &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"ssh_proxy_username":           &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"ssh_proxy_password":           &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"ssh_keep_alive_interval":      &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"ssh_read_write_timeout":       &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		// WinRM-specific configuration fields
		"winrm_username": &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"winrm_password": &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"winrm_host":     &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"winrm_no_proxy": &hcldec.AttrSpec{Name: "winrm_no_proxy", Type: cty.Bool, Required: false},
		"winrm_port":     &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"winrm_timeout":  &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"winrm_use_ssl":  &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"winrm_insecure": &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"winrm_use_ntlm": &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		// Shutdown configuration fields
		"shutdown_command": &hcldec.AttrSpec{Name: "shutdown_command", Type: cty.String, Required: false},
		"shutdown_timeout": &hcldec.AttrSpec{Name: "shutdown_timeout", Type: cty.String, Required: false},
		// Power-on timeout configuration fields
		"power_on_timeout": &hcldec.AttrSpec{Name: "power_on_timeout", Type: cty.String, Required: false},
		"boot_timeout":     &hcldec.AttrSpec{Name: "boot_timeout", Type: cty.String, Required: false},
		// ClusterConfig fields
		"vergeio_username": &hcldec.AttrSpec{Name: "vergeio_username", Type: cty.String, Required: false},
		"vergeio_password": &hcldec.AttrSpec{Name: "vergeio_password", Type: cty.String, Required: false},
		"vergeio_insecure": &hcldec.AttrSpec{Name: "vergeio_insecure", Type: cty.Bool, Required: false},
		"vergeio_endpoint": &hcldec.AttrSpec{Name: "vergeio_endpoint", Type: cty.String, Required: false},
		"vergeio_port":     &hcldec.AttrSpec{Name: "vergeio_port", Type: cty.Number, Required: false},
		// VmConfig fields
		"machine":                &hcldec.AttrSpec{Name: "machine", Type: cty.Number, Required: false},
		"name":                   &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"cluster":                &hcldec.AttrSpec{Name: "cluster", Type: cty.String, Required: false},
		"description":            &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"enabled":                &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
		"machine_type":           &hcldec.AttrSpec{Name: "machine_type", Type: cty.String, Required: false},
		"allow_hotplug":          &hcldec.AttrSpec{Name: "allow_hotplug", Type: cty.Bool, Required: false},
		"disable_powercycle":     &hcldec.AttrSpec{Name: "disable_powercycle", Type: cty.Bool, Required: false},
		"cpu_cores":              &hcldec.AttrSpec{Name: "cpu_cores", Type: cty.Number, Required: false},
		"cpu_type":               &hcldec.AttrSpec{Name: "cpu_type", Type: cty.String, Required: false},
		"ram":                    &hcldec.AttrSpec{Name: "ram", Type: cty.Number, Required: false},
		"console":                &hcldec.AttrSpec{Name: "console", Type: cty.String, Required: false},
		"display":                &hcldec.AttrSpec{Name: "display", Type: cty.String, Required: false},
		"video":                  &hcldec.AttrSpec{Name: "video", Type: cty.String, Required: false},
		"sound":                  &hcldec.AttrSpec{Name: "sound", Type: cty.String, Required: false},
		"os_family":              &hcldec.AttrSpec{Name: "os_family", Type: cty.String, Required: false},
		"os_description":         &hcldec.AttrSpec{Name: "os_description", Type: cty.String, Required: false},
		"rtc_base":               &hcldec.AttrSpec{Name: "rtc_base", Type: cty.String, Required: false},
		"boot_order":             &hcldec.AttrSpec{Name: "boot_order", Type: cty.String, Required: false},
		"console_pass_enabled":   &hcldec.AttrSpec{Name: "console_pass_enabled", Type: cty.Bool, Required: false},
		"console_pass":           &hcldec.AttrSpec{Name: "console_pass", Type: cty.String, Required: false},
		"usb_tablet":             &hcldec.AttrSpec{Name: "usb_tablet", Type: cty.Bool, Required: false},
		"uefi":                   &hcldec.AttrSpec{Name: "uefi", Type: cty.Bool, Required: false},
		"secure_boot":            &hcldec.AttrSpec{Name: "secure_boot", Type: cty.Bool, Required: false},
		"serial_port":            &hcldec.AttrSpec{Name: "serial_port", Type: cty.Bool, Required: false},
		"boot_delay":             &hcldec.AttrSpec{Name: "boot_delay", Type: cty.Number, Required: false},
		"preferred_node":         &hcldec.AttrSpec{Name: "preferred_node", Type: cty.String, Required: false},
		"snapshot_profile":       &hcldec.AttrSpec{Name: "snapshot_profile", Type: cty.String, Required: false},
		"cloud_init_data_source": &hcldec.AttrSpec{Name: "cloud_init_data_source", Type: cty.String, Required: false},
		"power_state":            &hcldec.AttrSpec{Name: "power_state", Type: cty.Bool, Required: false},
		"guest_agent":            &hcldec.AttrSpec{Name: "guest_agent", Type: cty.Bool, Required: false},
		"ha_group":               &hcldec.AttrSpec{Name: "ha_group", Type: cty.String, Required: false},
		"advanced":               &hcldec.AttrSpec{Name: "advanced", Type: cty.String, Required: false},
		"nested_virtualization":  &hcldec.AttrSpec{Name: "nested_virtualization", Type: cty.Bool, Required: false},
		"disable_hypervisor":     &hcldec.AttrSpec{Name: "disable_hypervisor", Type: cty.Bool, Required: false},
		"vm_disks":               &hcldec.BlockListSpec{TypeName: "vm_disks", Nested: hcldec.ObjectSpec((*FlatVmDiskConfig)(nil).HCL2Spec())},
		"vm_nics":                &hcldec.BlockListSpec{TypeName: "vm_nics", Nested: hcldec.ObjectSpec((*FlatVmNicConfig)(nil).HCL2Spec())},
		"cloud_init_files":       &hcldec.BlockListSpec{TypeName: "cloud_init_files", Nested: hcldec.ObjectSpec((*FlatCloudInitFile)(nil).HCL2Spec())},
	}
	return s
}

// HCL2Spec returns the hcl spec of a VmDiskConfig.
func (*FlatVmDiskConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"machine":               &hcldec.AttrSpec{Name: "machine", Type: cty.Number, Required: false},
		"name":                  &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description":           &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"interface":             &hcldec.AttrSpec{Name: "interface", Type: cty.String, Required: false},
		"media":                 &hcldec.AttrSpec{Name: "media", Type: cty.String, Required: false},
		"media_source":          &hcldec.AttrSpec{Name: "media_source", Type: cty.Number, Required: false},
		"preferred_tier":        &hcldec.AttrSpec{Name: "preferred_tier", Type: cty.String, Required: false},
		"disksize":              &hcldec.AttrSpec{Name: "disksize", Type: cty.Number, Required: false},
		"enabled":               &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
		"readonly":              &hcldec.AttrSpec{Name: "readonly", Type: cty.Bool, Required: false},
		"serial":                &hcldec.AttrSpec{Name: "serial", Type: cty.String, Required: false},
		"asset":                 &hcldec.AttrSpec{Name: "asset", Type: cty.String, Required: false},
		"orderid":               &hcldec.AttrSpec{Name: "orderid", Type: cty.Number, Required: false},
		"preserve_drive_format": &hcldec.AttrSpec{Name: "preserve_drive_format", Type: cty.Bool, Required: false},
	}
	return s
}

// HCL2Spec returns the hcl spec of a VmNicConfig.
func (*FlatVmNicConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"machine":          &hcldec.AttrSpec{Name: "machine", Type: cty.Number, Required: false},
		"name":             &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description":      &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"interface":        &hcldec.AttrSpec{Name: "interface", Type: cty.String, Required: false},
		"driver":           &hcldec.AttrSpec{Name: "driver", Type: cty.String, Required: false},
		"model":            &hcldec.AttrSpec{Name: "model", Type: cty.String, Required: false},
		"vnet":             &hcldec.AttrSpec{Name: "vnet", Type: cty.Number, Required: false},
		"macaddress":       &hcldec.AttrSpec{Name: "macaddress", Type: cty.String, Required: false},
		"ipaddress":        &hcldec.AttrSpec{Name: "ipaddress", Type: cty.String, Required: false},
		"assign_ipaddress": &hcldec.AttrSpec{Name: "assign_ipaddress", Type: cty.Bool, Required: false},
		"enabled":          &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
	}
	return s
}

// HCL2Spec returns the hcl spec of a CloudInitFile.
func (*FlatCloudInitFile) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":     &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"contents": &hcldec.AttrSpec{Name: "contents", Type: cty.String, Required: false},
		"files":    &hcldec.AttrSpec{Name: "files", Type: cty.List(cty.String), Required: false},
	}
	return s
}
