// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package vergeio

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatNetworkConfig is an auto-generated flat version of NetworkConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkConfig struct {
	Username   *string `mapstructure:"vergeio_username" required:"true" cty:"vergeio_username" hcl:"vergeio_username"`
	Password   *string `mapstructure:"vergeio_password" required:"true" cty:"vergeio_password" hcl:"vergeio_password"`
	Endpoint   *string `mapstructure:"vergeio_endpoint" required:"true" cty:"vergeio_endpoint" hcl:"vergeio_endpoint"`
	Port       *int    `mapstructure:"vergeio_port" required:"false" cty:"vergeio_port" hcl:"vergeio_port"`
	Insecure   *bool   `mapstructure:"vergeio_insecure" required:"false" cty:"vergeio_insecure" hcl:"vergeio_insecure"`
	FilterName *string `mapstructure:"filter_name" required:"false" cty:"filter_name" hcl:"filter_name"`
	FilterType *string `mapstructure:"filter_type" required:"false" cty:"filter_type" hcl:"filter_type"`
}

// FlatMapstructure returns a new FlatNetworkConfig.
// FlatNetworkConfig is an auto-generated flat version of NetworkConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkConfig)
}

// HCL2Spec returns the hcl spec of a NetworkConfig.
// This spec is used by HCL to read the fields of NetworkConfig.
// The decoded values from this spec will then be applied to a FlatNetworkConfig.
func (*FlatNetworkConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"vergeio_username": &hcldec.AttrSpec{Name: "vergeio_username", Type: cty.String, Required: true},
		"vergeio_password": &hcldec.AttrSpec{Name: "vergeio_password", Type: cty.String, Required: true},
		"vergeio_endpoint": &hcldec.AttrSpec{Name: "vergeio_endpoint", Type: cty.String, Required: true},
		"vergeio_port":     &hcldec.AttrSpec{Name: "vergeio_port", Type: cty.Number, Required: false},
		"vergeio_insecure": &hcldec.AttrSpec{Name: "vergeio_insecure", Type: cty.Bool, Required: false},
		"filter_name":      &hcldec.AttrSpec{Name: "filter_name", Type: cty.String, Required: false},
		"filter_type":      &hcldec.AttrSpec{Name: "filter_type", Type: cty.String, Required: false},
	}
	return s
}

// FlatNetworkInfo is an auto-generated flat version of NetworkInfo.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkInfo struct {
	ID          *int32  `mapstructure:"id" cty:"id" hcl:"id"`
	Name        *string `mapstructure:"name" cty:"name" hcl:"name"`
	Description *string `mapstructure:"description" cty:"description" hcl:"description"`
}

// FlatMapstructure returns a new FlatNetworkInfo.
// FlatNetworkInfo is an auto-generated flat version of NetworkInfo.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkInfo) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkInfo)
}

// HCL2Spec returns the hcl spec of a NetworkInfo.
// This spec is used by HCL to read the fields of NetworkInfo.
// The decoded values from this spec will then be applied to a FlatNetworkInfo.
func (*FlatNetworkInfo) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":          &hcldec.AttrSpec{Name: "id", Type: cty.Number, Required: false},
		"name":        &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description": &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
	}
	return s
}

// FlatNetworkOutput is an auto-generated flat version of NetworkOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkOutput struct {
	Networks []FlatNetworkInfo `mapstructure:"networks" cty:"networks" hcl:"networks"`
}

// FlatMapstructure returns a new FlatNetworkOutput.
// FlatNetworkOutput is an auto-generated flat version of NetworkOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkOutput)
}

// HCL2Spec returns the hcl spec of a NetworkOutput.
// This spec is used by HCL to read the fields of NetworkOutput.
// The decoded values from this spec will then be applied to a FlatNetworkOutput.
func (*FlatNetworkOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"networks": &hcldec.BlockListSpec{TypeName: "networks", Nested: hcldec.ObjectSpec((*FlatNetworkInfo)(nil).HCL2Spec())},
	}
	return s
}